### ISSUE TITLE
Error compiling *shell.ino in linux

### ISSUE THREAD

**Issue by prof-braino** [salsanci/YRShell#3]
Compiling using the Arduino IDE:

Arduino: 1.8.4 (Linux), Board: "Nucleo-64, Nucleo L476RG, Mass Storage, None, None"

In file included from /home/yrshell/Arduino/libraries/YRShell/utility/YRShellInterpreter.h:21:0,
                 from /home/yrshell/Arduino/libraries/YRShell/YRShell.h:4,
                 from /home/yrshell/Arduino/libraries/YRShell/examples/multipleShells/multipleShells.ino:2:
/home/yrshell/Arduino/libraries/YRShell/utility/Dictionary.h:5:29: fatal error: processorGlobal.h: No such file or directory
 #include "processorGlobal.h"
                             ^
compilation terminated.
exit status 1
Error compiling for board Nucleo-64.

This report would have more information with
"Show verbose output during compilation"
option enabled in File -> Preferences.

**Comment by prof-braino** [comment]
The command line compilation using make appear to work ok.

**Comment by prof-braino** [comment]
verified the version 20170918 mutipleshells compiles, loads and runs
verified the version 20170918 testshell compiles, loads and runs

**Comment by prof-braino** [comment]
verified the version 20171011 mutipleshells compiles, loads and runs
verified the version 20171011 testshell compiles, loads and runs

**Comment by prof-braino** [comment]
verified the version 20171018 mutipleshells does not compile

**Comment by prof-braino** [comment]
Tested - version 0.2 working on Linux Mint 18.1
